

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const BUY_COURSES_SUCCESS = 'BUY_COURSES_SUCCESS';
export const BUY_COURSES_FAIL = 'BUY_COURSES_FAIL';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';
