// src/redux/types/chapterTypes.js

export const FETCH_CHAPTERS_REQUEST = 'FETCH_CHAPTERS_REQUEST';
export const FETCH_CHAPTERS_SUCCESS = 'FETCH_CHAPTERS_SUCCESS';
export const FETCH_CHAPTERS_FAILURE = 'FETCH_CHAPTERS_FAILURE';

export const SET_CHAPTER_ID = 'SET_CHAPTER_ID';
export const ADD_CHAPTER_SUCCESS = 'ADD_CHAPTER_SUCCESS';
export const REMOVE_CHAPTER_SUCCESS = 'REMOVE_CHAPTER_SUCCESS';

export const UPDATE_CHAPTER_REQUEST = 'UPDATE_CHAPTER_REQUEST';
export const UPDATE_CHAPTER_SUCCESS = 'UPDATE_CHAPTER_SUCCESS';
export const UPDATE_CHAPTER_FAILURE = 'UPDATE_CHAPTER_FAILURE';
export const UPDATE_CHAPTER_ORDER_REQUEST = 'UPDATE_CHAPTER_ORDER_REQUEST';
export const UPDATE_CHAPTER_ORDER_SUCCESS = 'UPDATE_CHAPTER_ORDER_SUCCESS';
export const UPDATE_CHAPTER_ORDER_FAILURE = 'UPDATE_CHAPTER_ORDER_FAILURE';
