export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';
export const RESET_COURSE = 'RESET_COURSE';
export const SUBMIT_COURSE = 'SUBMIT_COURSE';
export const SUBMIT_COURSE_SUCCESS = 'SUBMIT_COURSE_SUCCESS';
export const SUBMIT_COURSE_FAILURE = 'SUBMIT_COURSE_FAILURE';

// src/redux/types.js

export const FETCH_USER_COURSES_REQUEST = 'FETCH_USER_COURSES_REQUEST';
export const FETCH_USER_COURSES_SUCCESS = 'FETCH_USER_COURSES_SUCCESS';
export const FETCH_USER_COURSES_FAILURE = 'FETCH_USER_COURSES_FAILURE';


export const FETCH_COURSE_DETAIL = 'FETCH_COURSE_DETAIL';
export const FETCH_COURSE_DETAIL_SUCCESS = 'FETCH_COURSE_DETAIL_SUCCESS';
export const FETCH_COURSE_DETAIL_FAILURE = 'FETCH_COURSE_DETAIL_FAILURE';
export const APPROVE_COURSE_SUCCESS = 'APPROVE_COURSE_SUCCESS'