export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';
export const RESET_COURSE = 'RESET_COURSE';
export const SUBMIT_COURSE = 'SUBMIT_COURSE';
export const SUBMIT_COURSE_SUCCESS = 'SUBMIT_COURSE_SUCCESS';
export const SUBMIT_COURSE_FAILURE = 'SUBMIT_COURSE_FAILURE';

