export const ADD_TO_FAVORITE_REQUEST = 'ADD_TO_FAVORITE_REQUEST';
export const ADD_TO_FAVORITE_SUCCESS = 'ADD_TO_FAVORITE_SUCCESS';
export const ADD_TO_FAVORITE_FAILURE = 'ADD_TO_FAVORITE_FAILURE';

export const REMOVE_FROM_FAVORITE_REQUEST = 'REMOVE_FROM_FAVORITE_REQUEST';
export const REMOVE_FROM_FAVORITE_SUCCESS = 'REMOVE_FROM_FAVORITE_SUCCESS';
export const REMOVE_FROM_FAVORITE_FAILURE = 'REMOVE_FROM_FAVORITE_FAILURE';

export const FETCH_FAVORITES_REQUEST = 'FETCH_FAVORITES_REQUEST';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAILURE = 'FETCH_FAVORITES_FAILURE';
