// src/redux/types/lessonTypes.js

export const FETCH_LESSONS_REQUEST = 'FETCH_LESSONS_REQUEST';
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS';
export const FETCH_LESSONS_FAILURE = 'FETCH_LESSONS_FAILURE';

export const ADD_LESSON_REQUEST = 'ADD_LESSON_REQUEST';
export const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS';
export const ADD_LESSON_FAILURE = 'ADD_LESSON_FAILURE';
export const DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
export const DELETE_LESSON_FAILURE = 'DELETE_LESSON_FAILURE';


export const FETCH_LESSONID_REQUEST = 'FETCH_LESSONID_REQUEST';
export const FETCH_LESSONID_SUCCESS = 'FETCH_LESSONID_SUCCESS';
export const FETCH_LESSONID_FAILURE = 'FETCH_LESSONID_FAILURE';
