export const COMPLETE_LESSON_REQUEST = 'COMPLETE_LESSON_REQUEST';
export const COMPLETE_LESSON_SUCCESS = 'COMPLETE_LESSON_SUCCESS';
export const COMPLETE_LESSON_FAILURE = 'COMPLETE_LESSON_FAILURE';
export const FETCH_LESSON_COMPLETE_REQUEST = 'FETCH_LESSON_COMPLETE_REQUEST';
export const FETCH_LESSON_COMPLETE_SUCCESS = 'FETCH_LESSON_COMPLETE_SUCCESS';
export const FETCH_LESSON_COMPLETE_FAILURE = 'FETCH_LESSON_COMPLETE_FAILURE';
