export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAILURE = 'PROFILE_CREATE_FAILURE';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE';

export const PROFILE_CHECK_DUPLICATE_REQUEST = 'PROFILE_CHECK_DUPLICATE_REQUEST';
export const PROFILE_CHECK_DUPLICATE_SUCCESS = 'PROFILE_CHECK_DUPLICATE_SUCCESS';
export const PROFILE_CHECK_DUPLICATE_FAILURE = 'PROFILE_CHECK_DUPLICATE_FAILURE';


export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAILURE = 'PROFILE_FETCH_FAILURE';

// profileActionTypes.js
export const UPLOAD_AVATAR_REQUEST = 'UPLOAD_AVATAR_REQUEST';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAILURE = 'UPLOAD_AVATAR_FAILURE';

export const PROFILE_STATS_FETCH_REQUEST = 'PROFILE_STATS_FETCH_REQUEST';
export const PROFILE_STATS_FETCH_SUCCESS = 'PROFILE_STATS_FETCH_SUCCESS';
export const PROFILE_STATS_FETCH_FAILURE = 'PROFILE_STATS_FETCH_FAILURE';