export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAILURE = 'PROFILE_CREATE_FAILURE';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE';

export const PROFILE_CHECK_DUPLICATE_REQUEST = 'PROFILE_CHECK_DUPLICATE_REQUEST';
export const PROFILE_CHECK_DUPLICATE_SUCCESS = 'PROFILE_CHECK_DUPLICATE_SUCCESS';
export const PROFILE_CHECK_DUPLICATE_FAILURE = 'PROFILE_CHECK_DUPLICATE_FAILURE';
