export const FETCH_TOTAL_SALARY = 'FETCH_TOTAL_SALARY';
export const FETCH_TOTAL_SALARY_SUCCESS = 'FETCH_TOTAL_SALARY_SUCCESS';
export const FETCH_TOTAL_SALARY_FAILURE = 'FETCH_TOTAL_SALARY_FAILURE';

export const FETCH_INSTRUCTOR_SALARY_BY_ID = 'FETCH_INSTRUCTOR_SALARY_BY_ID';
export const FETCH_INSTRUCTOR_SALARY_BY_ID_SUCCESS = 'FETCH_INSTRUCTOR_SALARY_BY_ID_SUCCESS';
export const FETCH_INSTRUCTOR_SALARY_BY_ID_FAILURE = 'FETCH_INSTRUCTOR_SALARY_BY_ID_FAILURE';

export const FETCH_ADMIN_SALARY = 'FETCH_ADMIN_SALARY';
export const FETCH_ADMIN_SALARY_SUCCESS = 'FETCH_ADMIN_SALARY_SUCCESS';
export const FETCH_ADMIN_SALARY_FAILURE = 'FETCH_ADMIN_SALARY_FAILURE';

export const FETCH_INSTRUCTORS_SALARY = 'FETCH_INSTRUCTORS_SALARY';
export const FETCH_INSTRUCTORS_SALARY_SUCCESS = 'FETCH_INSTRUCTORS_SALARY_SUCCESS';
export const FETCH_INSTRUCTORS_SALARY_FAILURE = 'FETCH_INSTRUCTORS_SALARY_FAILURE';

export const FETCH_INSTRUCTORS = 'FETCH_INSTRUCTORS';
export const FETCH_INSTRUCTORS_SUCCESS = 'FETCH_INSTRUCTORS_SUCCESS';
export const FETCH_INSTRUCTORS_FAILURE = 'FETCH_INSTRUCTORS_FAILURE';
