// userGoogleTypes.js
export const FETCH_USERGOOGLE_REQUEST = 'FETCH_USERGOOGLE_REQUEST';
export const FETCH_USERGOOGLE_SUCCESS = 'FETCH_USERGOOGLE_SUCCESS';
export const FETCH_USERGOOGLE_FAILURE = 'FETCH_USERGOOGLE_FAILURE';
export const DELETE_USERGOOGLE_REQUEST = 'DELETE_USERGOOGLE_REQUEST';
export const DELETE_USERGOOGLE_SUCCESS = 'DELETE_USERGOOGLE_SUCCESS';
export const DELETE_USERGOOGLE_FAILURE = 'DELETE_USERGOOGLE_FAILURE';
export const UPDATE_USERGOOGLE_REQUEST = 'UPDATE_USERGOOGLE_REQUEST';
export const UPDATE_USERGOOGLE_SUCCESS = 'UPDATE_USERGOOGLE_SUCCESS';
export const UPDATE_USERGOOGLE_FAILURE = 'UPDATE_USERGOOGLE_FAILURE';
