// userGoogleTypes.js
export const FETCH_USERGOOGLE_REQUEST = 'FETCH_USERGOOGLE_REQUEST';
export const FETCH_USERGOOGLE_SUCCESS = 'FETCH_USERGOOGLE_SUCCESS';
export const FETCH_USERGOOGLE_FAILURE = 'FETCH_USERGOOGLE_FAILURE';

export const UPDATE_USERGOOGLE_REQUEST = 'UPDATE_USERGOOGLE_REQUEST';
export const UPDATE_USERGOOGLE_SUCCESS = 'UPDATE_USERGOOGLE_SUCCESS';
export const UPDATE_USERGOOGLE_FAILURE = 'UPDATE_USERGOOGLE_FAILURE';

export const UPDATE_USERGOOGLE_PICURL_REQUEST = 'UPDATE_USERGOOGLE_PICURL_REQUEST';
export const UPDATE_USERGOOGLE_PICURL_SUCCESS = 'UPDATE_USERGOOGLE_PICURL_SUCCESS';
export const UPDATE_USERGOOGLE_PICURL_FAILURE = 'UPDATE_USERGOOGLE_PICURL_FAILURE';

export const BAN_USERGOOGLE_REQUEST = 'BAN_USERGOOGLE_REQUEST';
export const BAN_USERGOOGLE_SUCCESS = 'BAN_USERGOOGLE_SUCCESS';
export const BAN_USERGOOGLE_FAILURE = 'BAN_USERGOOGLE_FAILURE';

export const UNBAN_USERGOOGLE_REQUEST = 'UNBAN_USERGOOGLE_REQUEST';
export const UNBAN_USERGOOGLE_SUCCESS = 'UNBAN_USERGOOGLE_SUCCESS';
export const UNBAN_USERGOOGLE_FAILURE = 'UNBAN_USERGOOGLE_FAILURE';
